name: CI

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build test image
      run: docker buildx build --load -t ui-tests .

    - name: List Docker images (debug)
      run: docker image ls

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jre
        curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
        unzip allure.zip -d /opt/
        sudo ln -s /opt/allure-2.21.0/bin/allure /usr/bin/allure

    - name: Verify Allure Installation
      run: allure --version

    - name: Download previous report history
      run: |
        mkdir -p history
        git fetch origin gh-pages || echo "no gh-pages branch found"
        git checkout origin/gh-pages -- history || echo "no history found"
    
    - name: Merge Allure history
      run: |
        mkdir -p reports/history
        if [ -d "history" ] && [ "$(ls -A history)" ]; then
          cp -R history/* reports/history/
        else
          echo "No history to copy"
        fi

    - name: Run tests in Docker
      continue-on-error: true
      env:
        BASE_URL: ${{ vars.BASE_URL }}
        AUTH_USER_NAME: ${{ secrets.AUTH_USER_NAME }}
        AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
      run: |
        mkdir -p reports
        docker run --name ui-tests-container \
          -e BASE_URL="$BASE_URL" \
          -e AUTH_USER_NAME="$AUTH_USER_NAME" \
          -e AUTH_PASSWORD="$AUTH_PASSWORD" \
          -v ${{ github.workspace }}/reports:/tests/reports \
          -v ${{ github.workspace }}/videos:/tests/videos \
          ui-tests ./run.sh

    - name: Upload Allure raw results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: reports

    - name: Generate Allure Report
      run: allure generate reports -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
    
    - name: Send Teams Notification
      if: always()   # send even if tests fail
      run: |
        MESSAGE="UI Automation Tests Run Completed. \nAllure Report:
            https://alexkaminskiy.github.io/ui-automation-tests/"

            curl -H "Content-Type: application/json" \
                -d "{\"text\": \"${MESSAGE}\"}" \
                ${{ secrets.TEAMS_WEBHOOK_URL }}
    
    - name: Cleanup
      run: |
        docker rm -f ui-tests-container || true
        docker rmi -f ui-tests || true


    - name: Mark job as failed if tests failed
      if: failure()
      run: exit 1
